# Uses Regexes to determine which ED mappings belong to which groups

GroupMappings:
  General-InterfaceMode:
  # prefix
  - ^UI_.+$
  # complex
  - ^Cycle.+(Page|Panel)$

  General-GalaxyMap:
  # prefix
  - ^CamPitch.+$
  - ^CamTranslate.+$
  - ^CamYaw.+$
  - ^CamZoom.+$
  - ^(Pitch|Roll|Yaw)Camera.*$
  # exact
  - ^GalaxyMapHome$

  General-CameraSuite:
  # wildcard
  - ^.*FreeCam.*$
  # prefix
  - ^FStop.+$
  - ^PhotoCameraToggle.*$
  - ^(Pitch|Roll|Yaw)CameraMouse$
  - ^VanityCamera.+$
  # exact
  - ^FixCameraRelativeToggle$
  - ^FixCameraWorldToggle$
  - ^QuitCamera$
  - ^ToggleAdvanceMode$
  - ^ToggleRotationLock$
  # unkown
  # Relative Mouse Y-Axis
  
  General-HoloMe:
  # prefix
  - ^CommanderCreator.+$

  General-Playlist:
  # prefix
  - ^GalnetAudio_.+$

  General-StoreCamera:
  # prefix
  - ^Store.+$

  Ship-MouseControls:
  # complex
  - ^Mouse(X|Y)(Decay|Mode)$
  # exact
  - ^MouseDeadzone$
  - ^MouseDecayRate$
  - ^MouseGUI$
  - ^MouseLinearity$
  - ^MouseReset$
  - ^MouseSensitivity$

  Ship-FlightRotation:
  # prefix
  - ^PitchAxis.+$
  - ^RollAxis.+$
  - ^YawToRoll.+(?!Landing)$
  # complex
  - ^Pitch.+Button.*$
  - ^Roll.+Button.*$
  - ^Yaw.+Button.*$
  - ^Yaw(Left|Right)Button$
  # exact
  - ^YawAxisRaw$

  Ship-FlightThrust:
  - START HERE

  Ship:
  # wildcard
  - ^.*Thrust.*$
  # prefix
  - ^CycleFireGroup.+$
  - ^ExplorationSAA.+$
  - ^ExplorationFSS.+$
  - ^FSS.+$
  - ^Head(L|l)ook.+$
  - ^MouseHeadlook.*$
  - ^MouseTurret.+$
  - ^Radar.+$
  - ^SetSpeed.+$
  - ^SAA.+$
  - ^Target.+$
  - ^Throttle.+$
  # complex
  - ^(Primary|Secondary)Fire$
  - ^Cycle.+Subsystem$
  - ^Cycle.+Target.*$
  - ^Focus.+Panel$
  - ^Increase.+Power$
  - ^MultiCrew.+$
  - ^Order.+$
  # exact
  - ^ChargeECM$
  - ^CommsPanelFocusOptions$
  - ^DeployHardpointsOnFire$
  - ^DeployHardpointToggle$
  - ^DeployHeatSink$
  - ^DisableRotationCorrectToggle$
  - ^EngineColourToggle$
  - ^EjectAllCargo$
  - ^ExplorationFSSEnter$
  - ^FireChaffLauncher$
  - ^HMDReset$
  - ^Hyperspace$
  - ^HyperSuperCombination$
  - ^LandingGearToggle$
  - ^MotionHeadlook$
  - ^NightVisionToggle$
  - ^OpenCodexGoToDiscovery$
  - ^OpenOrders$
  - ^OrbitLinesToggle$
  - ^PhotoCameraToggle$
  - ^PlayerHUDModeToggle$
  - ^QuickCommsPanel$
  - ^RadarRangeAxis$
  - ^ResetPowerDistribution$
  - ^SelectHighestThreat$
  - ^SelectTarget$
  - ^SelectTargetsTarget$
  - ^ShipSpotLightToggle$
  - ^Supercruise$
  - ^SystemMapOpen$
  - ^TargetNextRouteSystem$
  - ^ToggleCargoScoop$
  - ^ToggleFlightAssist$
  - ^ToggleReverseThrottleInput$
  - ^TriggerFieldNeutraliser$
  - ^UIFocus(|Mode)$
  - ^UseAlternateFlightValuesToggle$
  - ^UseBoostJuice$
  - ^UseShieldCell$
  - ^WeaponColourToggle$
  - ^WingNavLock$
  - ^yawRotateHeadlook$

  SRV:
  # wildcard
  - ^.*Buggy.*$
  # prefix
  - ^Steer.+$
  # exact
  - ^DriveAssistDefault$
  - ^DriveSpeedAxis$
  - ^EnableMenuGroupsSRV$
  - ^ToggleDriveAssist$

  VoiceComm:
  # exact
  - ^CqcMuteButtonMode$
  - ^MicrophoneMute$
  - ^MuteButtonMode$

  OnFoot:
  # wildcard
  - ^.*Humanoid.*$
  # prefix
  # complex
  # exact
  - ^EnableMenuGroupsOnFoot$

  TODO:
  # prefix
  # exact
  - ^BackwardKey$
  - ^DecreaseSpeedButtonMax$ # driving?
  - ^DecreaseSpeedButtonPartial$ # driving?
  - ^EnableCameraLockOn$
  - ^EnableMenuGroups$
  - ^EnableRumbleTrigger$
  - ^ForwardKey$
  - ^FriendsMenu$
  - ^IncreaseSpeedButtonMax$ # driving?
  - ^IncreaseSpeedButtonPartial$ # driving?
  - ^Pause$
  - ^RecallDismissShip$ # driving?
  - ^ShowPGScoreSummaryInput$
  - ^ToggleButtonUpInput$

IgnoreList:
- KeyboardLayout